config/routes.rb
TheHoneyPieStarChart::Application.routes.draw do
  root :to => 'honey_pie#index'
  devise_for :users
  match 'enter_time' => 'honey_pie#enter_time'
  match 'buy' => 'honey_pie#buy', :as => :buy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :yoga, :gym, :meditation, :stars, :writing

  def self.convert_activities_to_stars
    all.each { |user| user.convert_activities_to_stars }
  end

  def convert_activities_to_stars
    if completed_minimum?
      minimum_reward
      extra_rewards
    end

    reset_activities
    save
  end

  def buy_prize stars_cost, prize
    response = {:success => 0}

    if stars >= stars_cost
      self.stars -= stars_cost
      send(prize + '=', send(prize) + 1)
      save

      response[:success] = 1
      response[:stars] = stars_cost
    end
    response

  end
  
  private
  def minimum_reward
    self.stars += 4
    self.yoga -= 1
    self.gym -= 1
    self.meditation -= 1
  end

  def extra_rewards
    self.stars += yoga * 2
    self.stars += gym * 3
    self.stars += meditation
    self.stars += writing * 3
  end


  def completed_minimum?
    yoga >= 1 and gym >= 1 and meditation >= 1
  end

  def reset_activities
    self.yoga = 0
    self.gym = 0
    self.meditation = 0
    self.writing = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/honey_pie_controller.rb
class HoneyPieController < ApplicationController

  before_filter :authenticate_user!
  def index
    @user = current_user
  end

  def enter_time
    user = current_user
    user.update_attributes params[:user]
    redirect_to root_path
  end

  def buy
    buy = params[:what]
    response = {:success => 0}

    if buy == 'tickets'
      response = current_user.buy_prize 16, 'movie_tickets'
    elsif buy == 'massage'
      response = current_user.buy_prize 4, 'massages'
    elsif buy == 'sundae'
      response = current_user.buy_prize 8, 'sundaes'
    elsif buy == 'dinner'
      response = current_user.buy_prize 20, 'dinner'
    elsif buy == 'popcorn'
      response = current_user.buy_prize 4, 'popcorn'
    elsif buy == 'taxi'
      response = current_user.buy_prize 6, 'taxi'
    end

    render :json => response.to_json
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/honey_pie_helper.rb
module HoneyPieHelper
end

app/views/honey_pie/index.html.erb
<script type="text/javascript">
$('#inner-content').removeClass('inner-content');
</script>
<div id="rewards-section">
  <div id="rewards-tab"><div class="rewards-text">Prizes</div></div>
  <div id="rewards">
    <div class="reward">
      &nbsp;&nbsp;4 x <span class="stars-cost-image"><%= image_tag("images/rating-star.png") %></span>
      <span class="reward-image"><%= link_to image_tag("images/massage.png"), buy_path(:what => :massage), :onclick => 'buy_prize("massage"); return false;' %></span>
    </div>
    <div class="reward">
      &nbsp;&nbsp;4 x <span class="stars-cost-image"><%= image_tag("images/rating-star.png") %></span>
      <span class="reward-image"><%= link_to image_tag("images/popcorn.png"), buy_path(:what => :popcorn), :onclick => 'buy_prize("popcorn"); return false;' %></span>
    </div>
    <div class="reward">
      &nbsp;&nbsp;8 x <span class="stars-cost-image"><%= image_tag("images/rating-star.png") %></span>
      <span class="reward-image"><%= link_to image_tag("images/sundae.png"), buy_path(:what => :sundae), :onclick => 'buy_prize("sundae"); return false;' %></span>
    </div>
    <div class="reward">
      &nbsp;&nbsp;6 x <span class="stars-cost-image"><%= image_tag("images/rating-star.png") %></span>
      <span class="reward-image"><%= link_to image_tag("images/taxi.png"), buy_path(:what => :taxi), :onclick => 'buy_prize("taxi"); return false;' %></span>
      <span class="sale"><%= image_tag("images/sale.png") %></span>
    </div>
    <div class="reward">
      16 x <span class="stars-cost-image"><%= image_tag("images/rating-star.png") %></span>
      <span class="reward-image"><%= link_to image_tag("images/tickets.png"), buy_path(:what => :tickets), :onclick => 'buy_prize("tickets"); return false;' %></span>
    </div>
    <div class="reward">
      20 x <span class="stars-cost-image"><%= image_tag("images/rating-star.png") %></span>
      <span class="reward-image"><%= link_to image_tag("images/dinner.png"), buy_path(:what => :dinner), :onclick => 'buy_prize("dinner"); return false;' %></span>
    </div>
  </div>
</div>

<div id="right-panel">
  <div id="stars">
    <% @user.stars.times do %>
    <%= image_tag "images/rating-star.png" %>
    <% end %>
    <br />
    <p>You have <span id="num-stars"><%= pluralize(@user.stars, 'star') %></span>.</p>
  </div>
  <br />
  <div id="prizes">
    <div id="tickets">
      <% @user.movie_tickets.times do %>
      <%= image_tag("images/tickets.png") %>
      <% end %>
    </div>
    <div id="taxi">
      <% @user.taxi.times do %>
      <%= image_tag("images/taxi.png") %>
      <% end %>
    </div>
    <div id="popcorn">
      <% @user.popcorn.times do %>
      <%= image_tag("images/popcorn.png") %>
      <% end %>
    </div>
    <div id="massage">
      <% @user.massages.times do %>
      <%= image_tag("images/massage.png") %>
      <% end %>
    </div>
    <div id="sundae">
      <% @user.sundaes.times do %>
      <%= image_tag("images/sundae.png") %>
      <% end %>
    </div>
    <div id="dinner">
      <% @user.dinner.times do %>
      <%= image_tag("images/dinner.png") %>
      <% end %>
    </div>
  </div>
</div>

<div id="activities">

  <%= form_tag('/enter_time', :method => "get") do %>
  <p>
    <%= image_tag "images/yoga.png" %>
    <%= image_tag "images/#{@user.yoga}.png", :id => 'yoga_num' %>
    <%= image_tag "images/up-arrow.png", :onclick => 'yogaUp();', :class => 'up-arrow'  %>
    <%= image_tag "images/up-arrow.png", :onclick => 'yogaDown();', :class => 'down-arrow flip-vertical' %>
    <%= text_field(:user, :yoga, :style => 'display: none;') %>
  </p>

  <p id="gym">
    <%= image_tag "images/gym.png" %>
    <%= image_tag "images/#{@user.gym}.png", :id => 'gym_num' %>
    <%= image_tag "images/up-arrow.png", :onclick => 'gymUp();', :class => 'up-arrow'  %>
    <%= image_tag "images/up-arrow.png", :onclick => 'gymDown();', :class => 'down-arrow flip-vertical' %>
    <%= text_field(:user, :gym, :style => 'display: none;') %>
  </p>

  <p>
    <%= image_tag "images/meditation.png" %>
    <%= image_tag "images/#{@user.meditation}.png", :id => 'meditation_num' %>
    <%= image_tag "images/up-arrow.png", :onclick => 'meditationUp();', :class => 'up-arrow'  %>
    <%= image_tag "images/up-arrow.png", :onclick => 'meditationDown();', :class => 'down-arrow flip-vertical' %>
    <%= text_field(:user, :meditation, :style => 'display: none;') %>
  </p>

  <p>
    <%= image_tag "images/writing.png" %>
    <%= image_tag "images/#{@user.writing}.png", :id => 'writing_num' %>
    <%= image_tag "images/up-arrow.png", :onclick => 'writingUp();', :class => 'up-arrow'  %>
    <%= image_tag "images/up-arrow.png", :onclick => 'writingDown();', :class => 'down-arrow flip-vertical' %>
    <%= text_field(:user, :writing, :style => 'display: none;') %>
  </p>

  <p>
    <%= submit_tag("Submit", :onclick => 'formSubmit();') %>
  </p>
  <% end %>
</div>

<script type="text/javascript">
var yogaNum = <%= @user.yoga %>;
var meditationNum = <%= @user.meditation %>;
var gymNum = <%= @user.gym %>;
var writingNum = <%= @user.writing %>;

function yogaUp() {
    yogaNum = up(yogaNum, '#yoga_num');
}

function yogaDown() {
    yogaNum = down(yogaNum, '#yoga_num');
}

function writingUp() {
    writingNum = up(writingNum, '#writing_num');
}

function writingDown() {
    writingNum = down(writingNum, '#writing_num');
}

function meditationUp() {
    meditationNum = up(meditationNum, '#meditation_num');
}

function meditationDown() {
    meditationNum = down(meditationNum, '#meditation_num');
}

function gymUp() {
    gymNum = up(gymNum, '#gym_num');
}

function gymDown() {
    gymNum = down(gymNum, '#gym_num');
}

function up(num, id) {
    if (num < 9) {
        num++;
    }
    changeSrc(num, id);
    return num;
}

function down(num, id) {
    if (num > 0)
        num--;
    changeSrc(num, id);
    return num;
}


function changeSrc(num, id) {
    if (num == 1)
        $(id).addClass('one');
    else
        $(id).removeClass('one');
    $(id)[0].src = '/assets/images/' + num + '.png';

    
}

function formSubmit() {
    $('#user_writing')[0].value = writingNum;
    $('#user_yoga')[0].value = yogaNum;
    $('#user_gym')[0].value = gymNum;
    $('#user_meditation')[0].value = meditationNum;
}

if (yogaNum == 1)
    $('#yoga_num').addClass('one');

if (gymNum == 1)
    $('#gym_num').addClass('one');

if (meditationNum == 1)
    $('#meditation_num').addClass('one');

if (writingNum == 1)
    $('#writing_num').addClass('one');


var out = false;
function rewards() {
    if (out == false) {
	config = {left: '+=230'};
	out = true;
    }
    else {
	config = {left: '-=230'};
	out = false;
    }
    $('#rewards-section').animate(config, 1000, function() {

    });

}

function buy_prize(what) {
    var r = confirm("HoneyPie, are you sure you want to buy this?");
    if (r == false)
	return false;

    $.post('<%= buy_path %>', {what: what}, 
	  function(data) {
	      if (data.success == 0) {
		  $('.alert').html('You do not have enough stars to buy this!');
		  return;
	      }
	      else {
		  var stars = $('#stars img');
		  var fadeStars = stars.slice(stars.length - data.stars);
		  fadeStars.fadeOut('slow', function() {
		      fadeStars.remove();
		  });
		  var numStars = $('#num-stars').html().match(/[0-9]+/)[0];
		  numStars -= data.stars;
		  var html = numStars + ' star';
		  if (numStars != 1)
		      html += 's';
		  $('#num-stars').html(html);

		  $('#' + what).append($('<img src="/assets/images/' + what + '.png" alt="' + what + '">'));
	      }
	  });
}

$('#rewards-tab').click(function() {
    rewards();
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>TheHoneyPieStarChart</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "stylesheets/main" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="content">
      <div id="banner">
	<%= image_tag "images/mario-glowstar.png", :class => 'star-left' %>
	<%= image_tag "images/banner.png", :class => 'banner' %>
	<%= image_tag "images/mario-glowstar.png", :class => ['flip-horizontal', 'star-right'] %>
      </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div id="inner-content" class="inner-content">
	<%= yield %>
      </div>
    </div>
  </body>
</html>